version: '3.2'

services:
  recipe-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      LANGUAGE: python
    ports:
      - "5002:5000"
    volumes:
      - type: bind
        source: .
        target: /app
