FROM python:3.9.6

ENV PYTHONBUFFERED 1

RUN apt-get -y update
RUN apt-get install -y python3-pip python3-dev python3-psycopg2 postgresql-client

RUN mkdir /app
WORKDIR /app

ADD . /app/

CMD ["./run.sh"]