version: '3.2'

services:
  recipe-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      LANGUAGE: python
    ports:
      - "5002:5000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db

  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/:z
